### ISSUE TITLE
Create a user input section

### ISSUE THREAD

**Issue by AnthonyV22298** [vargasarts/parlaypartay.davidvargas.me#3]
-User can type in away team, home team, percent chance of one of them winning
-This would help users that don't want to create algorithms, this way they can just type in everything regardless of sport
-I also imagine this does not take too much to implement and I can start testing the idea

**Comment by dvargasfuertes** [comment]
I think there will be two places to add manual inputs here within the strategies page:
- Instead of searching for matches, allow a user to add a match manually
- Instead of specifying an algorithm, allow a user to specify a manual value

**Comment by AnthonyV22298** [comment]
Yes that's exactly how I'm picturing it. This section should have user entered results, basically for each matchup selects the winner of each game for auto check results

**Comment by dvargasfuertes** [comment]
Just pushed a bunch of changes around to support inserting individual events:
- When you hit "new strategy" it's now recorded in the db and you go straight to the strategy/$id page
- Adding a game view the manual add or the search adds `events` records which is a new table.
- Adds/deletes are now writes to the DB

Still need to test and iterate on the generating of parlays that comes after that, while also allow specifying a manual value instead of the algorithm

**Comment by dvargasfuertes** [comment]
@AnthonyV22298 check out this demo: https://www.loom.com/share/ad35568f6f5743bf902a5ea3f2de0dba
